apiVersion: batch/v1
kind: Job
metadata:
  name: sd-bm-30-gpu
  namespace: research
  annotations:
    kueue.x-k8s.io/queue-name: user-gpu-queue
spec:
  completions: 5
  parallelism: 1
  template:
    metadata:
      labels:
        app: stable-diffusion
    spec:
      restartPolicy: Never
      containers:
        - name: sd-api
          image: docker.io/cheolhuikim/sd-api:v0.5
          args:
            - "A robot riding a horse"
            - "30"
          volumeMounts:
            - name: output-vol
              mountPath: /output
          resources:
            requests:
              cpu: "4"
              memory: 4Gi
              nvidia.com/gpu: 1
            limits:
              cpu: "6"
              memory: 6Gi
              nvidia.com/gpu: 1
          env:
            - name: SD_MODEL
              value: "/models/stable-diffusion-v1-4"
            - name: RUN_ENV
              value: "gpu"
      volumes:
        - name: output-vol
          emptyDir: {}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: sd-bm-30-cpu
  namespace: research
  annotations:
    kueue.x-k8s.io/queue-name: user-cpu-queue
spec:
  completions: 5
  parallelism: 1
  template:
    metadata:
      labels:
        app: stable-diffusion
    spec:
      restartPolicy: Never
      containers:
        - name: sd-api
          image: docker.io/cheolhuikim/sd-api:v0.5
          args:
            - "A robot riding a horse"
            - "30"
          volumeMounts:
            - name: output-vol
              mountPath: /output
          resources:
            requests:
              cpu: "4"
              memory: 4Gi
            limits:
              cpu: "6"
              memory: 6Gi
          env:
            - name: SD_MODEL
              value: "/models/stable-diffusion-v1-4"
            - name: RUN_ENV
              value: "cpu"
      volumes:
        - name: output-vol
          emptyDir: {}