apiVersion: v1
kind: ServiceAccount
metadata:
  name: quota-sa
  namespace: quota-api
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: quota-cq-reader
rules:
- apiGroups: ["kueue.x-k8s.io"]
  resources: ["clusterqueues"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: quota-cq-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: quota-cq-reader
subjects:
- kind: ServiceAccount
  name: quota-sa
  namespace: quota-api