apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: cpu-flavor
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: cpu-cluster-queue
spec:
  namespaceSelector: {} # match all.
  resourceGroups:
  - coveredResources: ["cpu", "memory"]
    flavors:
    - name: cpu-flavor
      resources:
      - name: cpu
        nominalQuota: 24
      - name: memory
        nominalQuota: 60Gi
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  namespace: research
  name: user-cpu-queue
spec:
  clusterQueue: cpu-cluster-queue