
apiVersion: v1
kind: Namespace
metadata:
  name: job-gw
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-gw-sa
  namespace: job-gw
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: job-gw-role
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list"]
- apiGroups: ["kueue.x-k8s.io"]
  resources: ["clusterqueues", "localqueues"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: job-gw-binding
subjects:
- kind: ServiceAccount
  name: job-gw-sa
  namespace: job-gw
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: job-gw-role