apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-gw
  namespace: job-gw
spec:
  replicas: 2
  selector:
    matchLabels:
      app: job-gw
  template:
    metadata:
      labels:
        app: job-gw
    spec:
      serviceAccountName: job-gw-sa
      containers:
      - name: gateway
        image: cheolhuikim/job-gw:v1.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: GPU_CQ
          value: gpu-cluster-queue
        - name: CPU_CQ
          value: cpu-cluster-queue
        - name: GPU_LQ
          value: user-gpu-queue
        - name: CPU_LQ
          value: user-cpu-queue
        - name: QUOTA_API_SVC
          value: http://quota-svc.quota-api.svc
        - name: JOB_NAMESPACE
          value: research
        - name: PENDING_THRESHOLD
          value: "10"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: job-gw
  namespace: job-gw
spec:
  selector:
    app: job-gw
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
